srcdir = .
prefix = /usr/local
exec_prefix=${prefix}
CC=gcc

CFLAGS=-I/usr/local/include  -Wall -O3

all: sfrsd.exe

encode_rs_int.o: encode_rs.c
	gcc -DBIGSYM=1 $(CFLAGS) -c -o $@ $^

decode_rs_int.o: decode_rs.c
	gcc -DBIGSYM=1 $(CFLAGS) -c -o $@ $^

init_rs_int.o: init_rs.c
	gcc -DBIGSYM=1 $(CFLAGS) -c -o $@ $^

sfrsd.exe: sfrsd.o encode_rs_int.o decode_rs_int.o init_rs_int.o
	gcc -g -DWIN32 -o $@ $^

clean:
	rm -f *.o *.a sfrsd.exe

